### ISSUE TITLE
* Perm doesn't work

### ISSUE THREAD

**Issue by HittmanA** [PurePlugins/PurePerms#234]

**Comment by HittmanA** [comment]
I am using php7 and I have my permission set to * however I have no perms and can't use op or other commands.

**Comment by kenygamer** [comment]
@HittmanA I would have asked you to explain your problem further. However, I understand what you are going through. The permission you are looking for is "pocketmine.command". But if you can't use /op (specifically) is because PurePerms brings with it a feature that helps to "prevent". Go to the config and edit this.
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by Borduni** [comment]
//closed
